name: Pipeline de Integração Contínua - AppMonitor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Verificação de Sintaxe
    runs-on: ubuntu-latest
    steps:
      - name: Clonar Repositório
        uses: actions/checkout@v3

      - name: Analisar sintaxe do script Bash
        run: bash -n status-check.sh

  test:
    name: Simulação de Testes
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Clonar Repositório
        uses: actions/checkout@v3

      - name: Rodar testes fictícios
        run: |
          echo "Executando testes simulados..."
          exit 0

  package:
    name: Empacotar Relatório
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clonar Repositório
        uses: actions/checkout@v3

      - name: Gerar arquivo report.zip
        run: |
          mkdir -p output
          echo "Este é um exemplo de relatório de testes." > output/test-summary.txt
          cp status-check.sh output/
          zip -r report.zip output/

      - name: Enviar artefato gerado
        uses: actions/upload-artifact@v4
        with:
          name: artefato-appmonitor
          path: report.zip
