name: Pipeline de Integração Contínua - AppMonitor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validação do Script
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Validar sintaxe do script
        run: |
          echo "::warning::Iniciando validação do script status-check.sh"
          bash -n status-check.sh || echo "::error::Erro de sintaxe encontrado!"

  test:
    name: Testes Simulados
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Executar testes fictícios
        run: |
          echo "[INFO] Executando testes..."
          echo "::warning::Este é apenas um teste simulado"
          exit 0

  package:
    name: Empacotar e Resumir
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Gerar arquivo report.zip
        run: |
          mkdir -p output
          echo "Resumo fictício dos testes." > output/test-report.txt
          cp status-check.sh output/
          zip -r report.zip output/

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-monitorado
          path: report.zip

      - name: Gerar summary
        run: |
          echo "### Relatório do CI" >> $GITHUB_STEP_SUMMARY
          echo "- Sistema operacional: \`${{ runner.os }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Branch analisada: \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Artefato gerado: [report.zip](./runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
